require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  DisplayCopNames: true
  NewCops: enable

Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Max: 90

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 125

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/ModuleLength:
  CountComments: false
  Max: 125

Metrics/PerceivedComplexity:
  Max: 7

Rails/FilePath:
  EnforcedStyle: slashes

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - pre
    - stg
    - demo

RSpec:
  Enabled: false

Style/AndOr:
  EnforcedStyle: always

RSpec/BeforeAfterAll:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SignalException:
  EnforcedStyle: semantic

Style/SingleLineBlockParams:
  Enabled: true
  Methods:
    - reduce:
        - a
        - e
    - inject:
        - a
        - e

Style/WordArray:
  MinSize: 0
  WordRegex: !ruby/regexp '/\A[\p{Word}]+\z/'

Style/SymbolArray:
  Enabled: false
